### PR TITLE
Twilio work

### PR DESCRIPTION
**Pull request by blackhat-hemsworth**
Updated the main twilio function that Priya had done so that it operates on two lists and returns a list of message send times from twilio API.

Added 3 functions to Send_Alerts.py - all are work in progress to varying degrees but figured I'd throw them out here as I won't get a chance to work any further til Monday. 
send_all_messages - the main one. Mostly calls other functions including the twilio one
get_phone_numbers - converts user IDs to phone numbers (right now this is pure filler because I don't know the REDcap setup)
update_user_table - 1. gets current messages sent & increments, 2. pushes updated messages sent + timestamp to signup table (#1 is done, #2 is not)

### CODE REVIEW

**Comment by RwHendrickson** [comment]
This is awesome! I'll work on reviewing it this weekend!

**Review by RwHendrickson — CHANGES_REQUESTED** [review]
Looks great! Only thing I would ask is to add *.DS_Store and *.cpython-310.pyc to gitignore

**Comment by blackhat-hemsworth** [comment]
Made changes and also added some formatting (#~~~~~) between my Send Alerts functions

**Review by RwHendrickson — APPROVED** [review]
Looks great! The .DS_Store & .pyc files are still in here, but I'm going to accept the merge and delete them after.

Thank you!

**Pull request merged**
